batch_size: 8
num_epochs: 20
lr: 0.0001
seq_len: 650
d_model: 512
n_times: 6
h: 8
dropout: 0.1
d_ff: 2048
src_lang: en
tgt_lang: fr
preload: 0
model_folder: weights
model_filename: tmodel_
tokenizer_file: tokenizer_{0}.json
experiment_name: runs/tmodel
