batch_size: 8
num_epochs: 20
lr: 1e-4
seq_len: 650
d_model: 512
n_times: 6
h: 8
dropout: 0.1
d_ff: 2048
lang_src: en
lang_tgt: fr
preload: 0
model_folder: weights
model_filename: tmodel_
tokenizer_file: tokenizer_{0}.json
experiment_name: runs/tmodel
